### ISSUE TITLE
Erro ao adicionar novo host

### ISSUE THREAD

**Issue by bmmatusiak** [nicolascb/nssh#2]
Olá Nicolas, estou tendo este erro ao adicionar um novo host, uso fedora 27(x64), pode me ajudar?

✗ ERROR: rename /tmp/config_219edea013a3db087569b9835a2a52b9.nssh /root/.ssh/config: invalid cross-device link

Obrigado pela sua atenção.

**Comment by nicolascb** [comment]
Esse problema ocorre quando o /tmp está montado em uma partição diferente de onde está o arquivo sshconfig.
A release [v1.0.1](https://github.com/nicolascb/nssh/releases/tag/v1.0.1) corrige esse problema.

**Comment by bmmatusiak** [comment]
Testei a release v1.0.1 e deu certo! 
Obrigado!
