### ISSUE TITLE
✗ ERROR: Host [xxx] already exist

### ISSUE THREAD

**Issue by LiohMoeller** [nicolascb/nssh#3]
I am trying to add hosts using the add command like:

nssh add localhost root@localhost

The .ssh/config file is empty at this stage. No matter what I am trying to add I got an error:

✗ ERROR: Host [xxx] already exist

When I add hosts manually to the config file they are shown with the list command and can even be deleted. Only adding hosts does not work, no matter which way I try.

**Comment by nicolascb** [comment]
Hello,

Paste command output:

$ nssh -v
$ nssh add server01 root@localhost
$ cat ~/.ssh/config

**Comment by LiohMoeller** [comment]
version 1.0.2
nssh add server01 root@localhost
✗ ERROR: Host [server01] already exist
cat ~/.ssh/config -> empty

Permissions: -rw------- 1 myuser mygroup 0 Apr  5 10:40 /home/myuser/.ssh/config

**Comment by nicolascb** [comment]
Hello,

New release fix:

[1.0.3](https://github.com/nicolascb/nssh/releases/tag/1.0.3)

**Comment by LiohMoeller** [comment]
Works now, thanks. I have just noticed that

nssh add localhost root@localhost

creates an entry with the label local not localhost. Is this intended?
